zapier/visual-builder

- _site/quickstart/introduction.html
Not sure if this was intentional?
> Remove redundant Zapier?

- docs/_docs/apikey.md
- docs/_docs/auth.md
- docs/_docs/basic.md
- docs/_docs/digest.md
- docs/_docs/oauth.md
- docs/_docs/session.md
Change headings to h2 so that the ToC renders.  Correct and amend oauth 2 doc.
> Heading changes for ToC.  Minor OAuth correction.

- docs/_cli_tutorials/dynamic-dropdowns.md
This doc adds a video walkthrough of how to implement dynamic dropdowns in a CLI app.
> Add dynamic dropdowns walkthrough video

- docs/_cli_tutorials/hydration.md
This guide is meant to explain the "ins and outs" of hydration from a developer-facing perspective.
> Add hydration guide

- assets/stylesheets/vendor/_syntax-highlighting.scss
Place a horizontal scrollbar for code blocks.
> Able to scroll horizontally

- docs/_partners/integration-review-guidelines.md
Add redirect from /partners/app-review-guidelines/ to integration review guidelines doc.
> Add redirect

- docs/_docs/integration-checks-reference.md
Auto-generated from https://github.com/zapier/zapier/pull/31264.
> Add doc for check T001

- docs/_docs/integration-checks-reference.md
A user reported this typo here: https://secure.helpscout.net/conversation/965524726/1453138?folderId=77022 - just submitting a quick fix!
> Fix "sqaure" typo for M004

- docs/_cli_docs/docs.md
Mostly fixing typos here, but also fix a few links that either 404 or redirected in a way that didn't make sense IMO
> Scotts polishing

- docs/_partners/lifecycle-planning.md
This sets the timescale to something that is in line with our current response time.
> Update submission response time

- docs/_cli_docs/docs.md
- docs/_docs/export.md
- docs/_docs/vs.md
- docs/_legacy/docs.md
- docs/_legacy/scripting.md
- docs/_news/introducing-zapier-platform-ui.md
- docs/_partners/lifecycle-planning.md
- docs/_quickstart/test_complete.md
- index.md
> Typos and broken links

- docs/_partner_api/embedding.md
> update security embed block screenshot

- docs/_partners/faq.md
- docs/_partners/integration-review-guidelines.md
- docs/_partners/zap-templates.md
Update Copy to Change "Activate" to "Publish"
Fixes https://zapierorg.atlassian.net/browse/PDE-1377
Code PR: https://github.com/zapier/zapier/pull/37595
> Update Copy to Change "Activate" to "Publish"

- docs/_cli_docs/cli.md
- docs/_cli_docs/docs.md
Regenerate latest docs from zapier/zapier-platform.
> Regenerate CLI docs

- docs/_docs/input-designer.md
- docs/_docs/knownissues.md
- docs/_docs/zapier-intro.md
fixes #101, fixes #109, fixes #119, fixes #129
> fix typos and add a section

- docs/_docs/faq.md
Tried to explain that Code Mode supports Node via z.require, but you shouldn't use it.
> Update faq.md for info on z.require

- docs/_partners/faq.md
Instead of the Slack community
> [PDE-1643] Point to Zapier Community

- docs/_partner_api/embedding.md
- docs/_partners/zap-templates.md
Update the embed widget docs with the new option params.
https://zapierorg.atlassian.net/browse/PDI-796?atlOrigin=eyJpIjoiYTlkMGI4N2E0MzIzNDA4N2IzOTM2YTczMDQwNjQwYmMiLCJwIjoiaiJ9
> [PDI-796] Update the embed widget docs with the new options

- docs/_partners/lifecycle-planning.md
Updated the JotForm link
https://zapierorg.atlassian.net/browse/PDE-1822
> Update lifecycle-planning.md (PDE-1822)

- docs/_partner_api/embedding.md
Removing the in page link to the embed docs.
> [PDI-809] Remove link to the embed widget docs

- docs/_partner_api/changelog.md
- docs/_partner_api/errors.md
I am not a wordsmith.  Feel free to critique as desired 😄 
Jira: https://zapierorg.atlassian.net/browse/PDI-847
Related PR: https://github.com/zapier/zapier/pull/46542
> PDI-847 Add rate limiting documentation

- docs/_legacy/import.md
When speaking with a developer about the conversion process, I realized that our list of things that differ in the new platform didn't mention file handling, which isn't a part of the Platform UI and is only available in the CLI.
While in the file I did a little cleanup, as I am wont to do.
> [SUPPORTESC-113] Add files to features that differ on the new platform, some cleanup

- docs/_partners/trusted-developers.md
Updating the list of Zapier Trusted App Developers to include GetUWired.
> Update Zapier Trusted App Developers - PDE-2017

- docs/_conversion/maintaining.md
- docs/_conversion/steps.md
- docs/_docs/triggers.md
- docs/_partners/feature-requests-bugs.md
remove hide and replace language. fix error in dedup description. add screenshots for convert steps
> PDE-2044 - fix errors and add screenshots

- docs/_partner_api/embedding.md
Added parameter to specify only Zap templates between specific apps (line 31)
https://zapier.slack.com/archives/CH0SN5V0V/p1614274742101500
> [TPS-934] Update embedding.md

- _includes/side-nav.html
- docs/_conversion/overview.md
- docs/_conversion/steps.md
> PDE-2057 Add self convert pages to left hand nav. 

- docs/_docs/faq.md
- docs/_docs/integration-checks-reference.md
- docs/_docs/triggers.md
Hopefully, this will help developers understand the details of why their data structures need to match.
I also retooled the REST Hook section a bit to make the incorporation there easier, as it was somewhat confusing on Perform vs Perform List.
> [SUPPORTESC-126] Add detail on sample data matching real data in the Platform docs

- docs/_partner_api/embedding.md
- docs/_partners/zap-templates.md
Based on some recent threads we need to add some cross references to our docs for handling the widget embeds in async envs.
> TPS-988 Make some minor improvements to our embeds docs.

- docs/_partner_api/embedding.md
Removed .md and added full URL to fix typo
> TPS-988 Updated URL to fix typo

- docs/_partner_api/changelog.md
- docs/_partner_api/endpoints.md
Jira: https://zapierorg.atlassian.net/browse/TPS-1041
⚠️  Do not merge until we release the actual feature to the public ⚠️ 
TODO:
[X] Update the date to the day we release the feature.
> TPS-1041 -- add uuid and label to partnerapi documentation

- docs/_docs/integration-checks-reference.md
The language on this check was a bit complex, so I've tried to preserve meaning while making it simpler.
Once this is approved, I'll port the changes to the main `zapier` repo too.
> [SUPPORTESC-166] Simplify the language of S003

- docs/_partners/partner-faq.md
Attached the ticket I was working on as I noticed this.
> [PDE-2493] Update partner count.

- docs/_docs/glossary.md
- docs/_docs/start.md
- docs/_docs/zapier-intro.md
- docs/_partners/partner-faq.md
- docs/_partners/planning-guide.md
- docs/_partners/zap-templates.md
- docs/_quickstart/introduction.md
I missed a lot in https://github.com/zapier/visual-builder/pull/214.
> [PDE-2390] Update all 1,300 references to 3,500.

- _config.yml
- docs/_docs/glossary.md
- docs/_docs/start.md
- docs/_docs/zapier-intro.md
- docs/_partners/partner-faq.md
- docs/_partners/planning-guide.md
- docs/_partners/zap-templates.md
- docs/_quickstart/introduction.md
Following up with good advice!
> [PDE-2390] Use app count via variables

- docs/_partners/feature-requests-bugs.md
Rephrase to refer to the sidebar accurately.
I'm paranoid admittedly.
> [SUPPORTESC-181] app -> integration.

- docs/_partner_api/changelog.md
- docs/_partner_api/endpoints.md
**DO NOT MERGE** until we release those updates.
Related issue: [TPS-1198](https://zapierorg.atlassian.net/browse/TPS-1198)
> TPS-1198: update docs for v1/zaps and v1/profiles/me

- docs/_cli_docs/docs.md
> SUPPORTESC-160: Regenerate CLI docs

- docs/_docs/triggers.md
Just keeping us honest here, as per https://zapier.com/pricing. 😄
> [SUPPORTESC-183] update valid polling intervals

- .github/CODEOWNERS
Set content designers as reviewers automatically.
> [PDE-2606] Request content designer's review automatically

- docs/_cli_docs/versions.md
- docs/_docs/versions.md
[Draft in Coda](https://coda.io/d/Partnerships-Playbook_dTV4Mw3AIaG/How-to-Update-an-App_sueu_#_luzNg)
> [PDE-2772] Manage Versions Additions

- docs/_cli_tutorials/versions.md
Just committed code in #232 is now moved under the CLI Tutorial Area
> [PDE-2772] Move Manage Versions

- docs/_embed/elements.md
We need to enable the TOC to the Elements page.
> [TPS-1427] Add TOC to elements page.

- docs/_embed/elements.md
Removed the duplicate Elements header and then updated the remaining headers
> [TPS-1427] Remove duplicate header

- docs/_embed/elements.md
- docs/_embed/overview.md
Addition of Embed Video YouTube Series
> [TPS-1427] Addition of Embed Video Series

- docs/_embed/partner_api.md
- Fix code snippet for passing multiple fields
- Add third example for providing a label for dropdowns
> [TPS-1427] Fix code for passing multiple fields

- docs/_cli_docs/docs.md
> [SUPPORTESC-160] Regenerate CLI docs

- docs/_embed/partner_api.md
Add postMessage and DELETE details to docs
> [TPS-1477] update partner embed docs

- docs/_embed/partner_api.md
> TPS-1350 Update v1/zaps docs to reflect support for 'limit' and 'offset'

- docs/_embed/automatic_account_creation.md
> [TPS-1535] Add auth code flow diagram

- docs/_docs/auth.md
Update the screenshot of auth scheme picket. https://platform.zapier.com/docs/auth
> [PDE-3004] Update screenshot of auth scheme picket.

- docs/_embed/elements.md
Removed references to legacy JS widget and updated screen shots
> [TPS-1645] - update docs with ZTE generator

- docs/_embed/partner_api.md
> [TPS-1638] Fix typo in partner docs

- docs/_docs/input-designer.md
More context in https://zapier.slack.com/archives/C0C4XGJC8/p1646856629255659
> [SUPPORTESC-313] Updating wording for Static Dropdowns

- docs/_embed/automatic_account_creation.md
> TPS-1707: fix misspelling in AAC docs

- docs/_docs/integration-checks-reference.md
Update D019 and D020 integration checks info to reflect updated UI and link to CLI Platform schema docs
> [PDE-3149] docs(ui): Update D019 and D020 Integration Checks Info

- docs/_docs/integration-checks-reference.md
Add further details to the S002 validation check about free trials/extensions for testing more than 5 triggers/actions/searches.
> [PDE-3149] docs(ui): Update S002 Integration Check

- docs/_partners/common-migration-errors.md
- docs/_partners/faq.md
* Updated the Zapier integration tips to be more relevant to our current app review processes
* Created a separate doc for Common Migration Errors (discussion [here](https://zapier.slack.com/archives/C03AR1WDR26/p1649834746258559?thread_ts=1649783743.619029&cid=C03AR1WDR26))
* Update the Deployment errors to be more specific to Migration Errors after chatting with David from dev platform on the new UI's [checks](https://zapier.slack.com/archives/C5Z9BP4U9/p1649788129906649).
* Confirmed existing hyperlinks work.
> [PDE-3149] Updates to the Zapier Integration TIps and FAQs

- docs/_docs/faq.md
Add resources for users using the Code Mode in the visual builder.
> PDE-3149 HackWeek: Update Code Mode FAQ with more resources

- Gemfile.lock
- README.md
- docs/_embed/automatic_account_creation.md
- docs/_embed/faqs.md
- docs/_embed/partner_api.md
- docs/_embed/security.md
- docs/_embed/zap_editor.md
I moved the "Zap Editor" section from the Partner API page to its own page.
I also updated the README, and did some minor a11y improvements.
> TPS-1715 Zap Editor page

- docs/_embed/elements.md
- docs/_embed/partner_api.md
[TPS-1706](https://zapierorg.atlassian.net/browse/TPS-1706)
Update instructions for obtaining a client id on the embed elements page and the partner API page
> [TPS-1706] update docs regarding obtaining your client id

- docs/_embed/partner_api.md
Add uuid to the app step payload from Partner API `v1/zaps` endpoints
> TPS-1769: Update partner_api.md

- docs/_partners/feature-requests-bugs.md
Updated language around making new versions.
> [SUPPORTESC-364] Update version language

- Gemfile.lock
- _config.yml
- docs/_partners/lifecycle-planning.md
- docs/_partners/partner-faq.md
* Update the `partner_count` template variable to highlight 5,000+ integrations
* Use the `partner_count` variable in some files where it was missing
> PDE-3237: Update Partner App count

- docs/_docs/integration-checks-reference.md
MR for update in monolith here: https://gitlab.com/zapier/zapier/-/merge_requests/50530
This takes care of the matching documentation for the M005 check here: https://platform.zapier.com/docs/integration-checks-reference#m005---developer-email-domain-matches-app-domain
> [SUPPORTENG-370] Add collaborator detail to M005 check

- docs/_partners/faq.md
Adding details about partner pledge to our docs
> [TPS-1913] - Adding details about partner pledge to our docs

- docs/_docs/integration-checks-reference.md
Updates the text for the D003 integration check in the docs for clarity, and matches it with the current text in the check itself.
> [SUPPORTENG-400] Update D003 text

- docs/_docs/versions.md
This is more or less a full re-write of the "Versions" page, based on feedback from Platform Support and reviewing developer questions from the last two quarters.
> [SUPPORTENG-377] Versions doc rewrite

- docs/_partners/planning-guide.md
New screenshots and hyperlinks for page https://platform.zapier.com/partners/planning-guide
Updated verbiage for secondary color (not currently in use).
> SUPPORTENG-408-update-integration-branding-guidelines

- docs/_cli_tutorials/getting-started.md
Updated invite and sharing commands, screenshots, example app hyperlinks.
> SUPPORTENG-374-cli_tutorial-gettingstarted-update

- docs/_partners/lifecycle-planning.md
Reference doc of changes: https://docs.google.com/document/d/1mZVk01P3v86X2jg4znfHXqOYW58lI610_o3W686LUgk/edit#
See comments tab in the doc for changes!
> [PARTOPS-220] Make updates to launch section of doc per partner marketing's request

- docs/_partners/integration-quality.md
- docs/_partners/zap-templates.md
Adding new content in future support of the Integration Insights dashboard. Additional content will be published once that feature is launched publicly!
https://zapierorg.atlassian.net/browse/PARTOPS-198
> [PARTOPS-198] Add new integration quality content

- docs/_docs/transfer.md
> [SUPPORTENG-405] Update transfer.md

- docs/_partners/feature-requests-bugs.md
Adding link to list of breaking changes in Versions section.
> SUPPORTENG-432_breakingchangeslinkadd

- docs/_partners/zap-templates.md
Updated images and hyperlinks
Removed broken wistia video
Added deprecation detail
> SUPPORTENG-436_updateZT

- docs/_docs/versions.md
Add change of key to the breaking change list.
> SUPPORTENG-432_addkeytobreakingchanges

- docs/_embed/zap_editor.md
Typo caught by one of our Typeform partners, who informed us.
> [PARTOPS-357] Fix Editor typo

- docs/_embed/automatic_account_creation.md
- docs/_embed/faqs.md
- docs/_embed/partner_api.md
- docs/_embed/security.md
- docs/_embed/zap_editor.md
- docs/_embed/zap_templates.md
[Reference of update](https://docs.google.com/document/d/1cdqRfFdaKrgThn3NGPi7Ealpn1Y41_9iyLetSnpoWzc/edit)
* Add Zap Templates doc
* Update page orderings
> [PARTOPS-278 ] Add zap template doc

- docs/_embed/elements.md
> [TPS-2093] Update Elements to be replaced with FZE

- docs/_embed/full_zapier_experience.md
adding a link to the dev platform
> [TPS-2093] adding a link to the dev platform

- docs/_embed/zap_templates.md
adding link to dev platform for ZTs
> [TPS-2093] adding link to dev platform for ZTs

- docs/_partners/trusted-developers.md
Per [request](https://zapier.slack.com/archives/C2BNYAX09/p1669055384413279) of Scott P. from the Experts team!
> [PARTOPS-177] Add Connex Digital as trusted developer

- docs/_partners/zap-templates.md
adding note re custom code, webhook and formatter steps not being allowed.
> SUPPORTENG-515_add_note_recustomsteps

- docs/_embed/partner_api.md
Per Cameron's [comment](https://zapier.slack.com/archives/C034FE1KP45/p1669136735498639) in this Slack thread.
> [PARTOPS-177] Add clarification the integration has to be public in Partner API docs

- _includes/head.html
- docs/_partners/lifecycle-planning.md
- Update copy and link to go to https://zapier.com/partner/solutions/plug-and-play
- Update example with ZTE
> Update embed widget option with the Full Zapier Experience

- _config.yml
- docs/_cli_docs/docs.md
Reverts zapier/visual-builder#377
> Revert "SUPPORTENG-537_add_cli_version_variable"

- _includes/head.html
- docs/_partners/lifecycle-planning.md
Fixed up the formatting and reduced spacing on this page here: https://platform.zapier.com/partners/lifecycle-planning#:~:text=Option%202%20The%20Partner%20API%3A%20Embed%20in%20a%20customized%20way%20to%20fit%20the%20style%20of%20your%20product
> Revert formatting on head.html and reduce space below ZTE example on Lifecycle Planning page

- docs/_cli_docs/cli.md
- docs/_cli_docs/docs.md
Copies the latest contents from https://github.com/zapier/zapier-platform to here.
> Regenerate CLI docs and update the version

- docs/_partners/partner-faq.md
https://zapier.slack.com/archives/C01JHGGJM7T/p1670545400248999
> [PARTOPS-465] Update Tip 8 of Partner Tips and FAQs to include FZE and Partner API

- docs/_embed/full_zapier_experience.md
- docs/_embed/zap_templates.md
- docs/_partners/partner-faq.md
Also update what was previously tip 5 regarding populating marketplace - https://zapier.slack.com/archives/C01JHGGJM7T/p1671634591548099?thread_ts=1670545400.248999&cid=C01JHGGJM7T
> [PARTOPS-465] Reorder partner tips so embedding is nearer the top

- docs/_partners/planning-guide.md
We no long collect secondary color info from Partners in the publishing form.
> [PARTOPS-487] Remove mention of secondary color

- docs/_cli_tutorials/hydration.md
This PR essentially reverts https://github.com/zapier/visual-builder/pull/385. It turns out that people read the doc!
Will update screenshots per https://github.com/zapier/visual-builder/pull/393 next!
> [SUPPORTENG-579] Restore hydration doc

- docs/_partners/integration-quality.md
The table is not rendering correctly. I'm trying to revert it back to markdown since there are other existing tables in the docs that are working.
> [PARTOPS-198] Update html table to markdown

- docs/_partners/integration-quality.md
The table is not rendering correctly. I'm trying to revert it back to markdown since there are other existing tables in the docs that are working.
> [PARTOPS-198] Remove list html tags

- docs/_partners/feature-requests-bugs.md
- docs/_partners/integration-quality.md
- docs/_partners/partner-faq.md
Update mention of integration insights in a few Partner platform docs
> [PARTOPS-481] Integration insights platform doc updates

- docs/_docs/vs.md
Internal context: https://zapier.slack.com/archives/C5Z9BP4U9/p1675791854164349
> [PDE-3773] Replace and update Visual Builder vs CLI comparison image in ui.md with Markdown table

- docs/_quickstart/invite_team_member.md
* Update the `Receive Integration Issue Notification Email` row to have a checkmark in the Collaborator column: 
* Replace all `X` with `-` in the table:
* Before:
* After:
> [TPS-2194] Update docs to mention that collaborators now receive integration issue emails

- docs/_docs/oauth.md
This is a reflective update of the copy fix made to auth redirect URI.
> [PDE-3777] Update copy of redirect uri of auth.

- docs/_partners/lifecycle-planning.md
Requested changes by partner marketing (Cass):
- Update text within the first section of [step 4](https://platform.zapier.com/partners/lifecycle-planning#4-launch-with-the-partner-program)
- Delete “A dedicated blog post, email, and social media campaign about the launch of your integration” 
- Delete “Get leads from your page in Zapiers App Directory” 
- Add “A shoutout about the launch of your integration in our [updates blog post](https://zapier.com/blog/all-articles/product-news/)” 
- Add “Access to your [integration health data](https://platform.zapier.com/partners/feature-requests-bugs#how-to-monitor-integration-insights)” 
- Add “A dedicated page in [Zapier’s App Directory](https://zapier.com/apps)”
Please add these above the last point
- Exposure within Zapier’s product and on the …
> [TPS-2232] Update launch benefits

- docs/_partners/zim.md
Add new page around Zapier Issue Manager
> SUPPORTENG-822 Add ZIM page to platform docs

- docs/_partners/zim.md
Fixing formatting
https://zapierorg.atlassian.net/browse/SUPPORTENG-823
> SUPPORTENG-823 Add bullet points to ZIM page

- docs/_docs/input-designer.md
SUPPORTENG-486_update_multiple_input_wording
> SUPPORTENG-486_update_multiple_input_wording

- docs/_partners/integration-quality.md
https://zapier.slack.com/archives/C034FE1KP45/p1677786879353429
> [PARTOPS-587] Update 'Active Users Retention' and 'Zap Activation Rates' to sentence-casing

- _includes/head.html
- docs/_partners/faq.md
- docs/_partners/feature-requests-bugs.md
- docs/_partners/integration-quality.md
- docs/_partners/lifecycle-planning.md
- docs/_partners/zim.md
https://zapierorg.atlassian.net/browse/SUPPORTENG-826
> SUPPORTENG-826 Add ZIM ZT

- docs/_embed/zap_editor.md
Slack context: https://zapier.slack.com/archives/CM1AX072B/p1677269244034309?thread_ts=1676591051.250539&cid=CM1AX072B
> [PARTOPS-582] Add section to Zap Editor embed regarding webintent editor URL and params

- docs/_docs/start.md
- docs/_embed/overview.md
- docs/_partners/lifecycle-planning.md
This PR adds documentation to recent changes around the Intended Audience field.
> Documentation around publishing trigger.

- docs/_zapier_products/natural_language_actions_api.md
- docs/_zapier_products/zapiers_chatgpt_plugin.md
Follow up from this PR: https://github.com/zapier/visual-builder/pull/430
> [UDOCS-1383] Followup: remove stray X symbol

- docs/_partners/integration-review-guidelines.md
- docs/_partners/planning-guide.md
Author:    Cameron Phillips <cameron.phillips@zapier.com>
https://zapierorg.atlassian.net/browse/UDOCS-1655
> Align branding guidelines

- docs/_partners/integration-quality.md
Adding embed insights to [this existing doc](https://platform.zapier.com/partners/integration-quality)
> [PARTOPS-646] Update integration-quality doc with embed insights

- docs/_zapier_products/natural_language_actions_api.md
Updated URL to sign up for NLA access.
> [UDOCS-1803] Update NLA form URL

- docs/_embed/partner_api.md
Summary of doc changes:
- Update query parameters of `v1/apps` to include `title_search`, `title_starts_with`, and `category`
- Update query parameter of `v1/zaps` to include `is_in_zap_template_with`.
- Added endpoint `/v1/categories` with description 
- Update changelog
> [TPS - 2404] Update Partner API documentation

- docs/_cli_docs/docs.md
Sync changes from https://github.com/zapier/zapier-platform/pull/655
> [SUPPORTENG-905] Update "OAuth2 with PKCE" section

- docs/_cli_docs/docs.md
Sync changes from `zapier/zapier-platform`, including  https://github.com/zapier/zapier-platform/pull/654
> [SUPPORTENG-907] Update "Output Fields" section

- docs/_embed/zap_editor.md
Minor formatting, spacing, and content edits after seeing it live on our platform docs.
> [PARTOPS-668] Small edits to prefill generator doc

- docs/_cli_docs/docs.md
- docs/_docs/oauth.md
following steps https://coda.io/d/Team-Developer-Platform_di0MgBhlCWf/Syncing-CLI-Docs_su6uK#_lu3fi
> SUPPORTENG-913_syncing_cli_docs

- docs/_embed/zap_editor.md
Updates the documented Zap Prefill URLs to match the new URL being introduced by:
- https://gitlab.com/zapier/partnerapi/-/merge_requests/269
- https://gitlab.com/zapier/team-developer-platform/dev-platform/-/merge_requests/1185
This MR is now ready for merge!
> TPS-2436 Update Zap Prefill URLs

- _includes/header.html
- docs/_build/hydration.md
Fixed Documentation header + amended article title
> [UDOCS-2004] fixed header and article title

- docs/_manage/invite-team-member.md
- docs/_reference/app-extensions-api-requests.md
https://zapierorg.atlassian.net/browse/SUPPORTENG-927
> SUPPORTENG-927 Integration Ownership/API Requests/App Extensions

- docs/_build/recommended-integration-features.md
Follow-up from this [PR](https://github.com/zapier/visual-builder/pull/496#pullrequestreview-1565767158) 🤦‍♀️ , where my add of the new doc failed to get committed, and I jumped the gun and merged after approval.
> [PARTOPS-203] Add moved file under build tab

- docs/_build/recommended-integration-features.md
Adding recommended T/A/S for additional app categories per [this project](https://coda.io/d/Partnerships-Playbook_dTV4Mw3AIaG/Top-T-A-S-by-App-Category_suDzK#_luwcr).
> [PARTOPS-768] Add new categories for recommended T/A/S

- docs/_publish/integration-brand-design-guidelines.md
https://zapierorg.atlassian.net/browse/SUPPORTENG-960
> [SUPPORTENG-960] Doc update: How to rebrand integration

- docs/_manage/invite-team-member.md
https://zapierorg.atlassian.net/browse/SUPPORTENG-966
> SUPPORTENG-966 Add Managing Partner Email Subscriptions to platform docs

- docs/_publish/zap-templates.md
https://zapierorg.atlassian.net/browse/SUPPORTENG-975
> SUPPORTENG-975 Remove references to assigning a status to ZT

- docs/_manage/account-and-team/add-team.md
- docs/_publish/zap-templates.md
https://zapierorg.atlassian.net/browse/SUPPORTENG-986
> SUPPORTENG-986 Add self-serve Collaborator

- docs/_embed/amplify-embed.md
- docs/_embed/faq.md
- docs/_embed/security.md
https://zapierorg.atlassian.net/browse/PLATSUP-987
Copy was proofed by Miranda from Partner Marketing
> PLATSUP-987 Amplify Embed

- docs/_embed/amplify-embed.md
https://zapierorg.atlassian.net/browse/PLATSUP-989
> PLATSUP-989 Update amplify embed layout

- docs/_embed/amplify-embed.md
https://zapierorg.atlassian.net/browse/PLATSUP-990
> PLATSUP-990 Amplify embed title

- docs/_embed/benefits-embedding.md
https://zapierorg.atlassian.net/browse/PLATSUP-993
> PLATSUP-993 Update amplify embed page name

- docs/_embed/benefits-embedding.md
https://zapierorg.atlassian.net/browse/PLATSUP-994
> PLATSUP-994 Fix amplify redirect

- docs/_embed/benefits-embedding.md
- docs/_embed/faq.md
- docs/_embed/quick-account-creation.md
- docs/_embed/security.md
Forgot the doc headers from this deploy - https://github.com/zapier/visual-builder/pull/538.
Updates the ordering of other docs on "Embed" tab.
> [PARTOPS-858] Add doc header and update position of other pages

- docs/_embed/quick-account-creation.md
* Swap Case study and Example implementation sections
* Fixed minor formatting and grammatical errors
> [PARTOPS-858] Fix small formatting + grammatical errors on QuAC docs

- docs/_quickstart/must-have-triggers-and-actions.md
- Renaming "Integration design examples" doc to "Much have triggers and actions" per partnerships conversation in [Slack](https://zapier.slack.com/archives/C034FE1KP45/p1701973376276929?thread_ts=1701962792.470319&cid=C034FE1KP45).
- Add redirect URL for previous URL
> [PARTOPS-861] Rename file to Must have triggers and actions

- docs/_reference/natural_language_actions_api.md
This is a follow-up to this [Pull Request](https://github.com/zapier/visual-builder/pull/558) as I forgot to update the heading there.
> [PLATSUP-1003] - Updated the AI Actions page title

- docs/_embed/quick-account-creation.md
Updates made per [this thread](https://zapier.slack.com/archives/CH0SN5V0V/p1702396899062609?thread_ts=1702327048.555189&cid=CH0SN5V0V) with Chris, Michelle, and Powell on TPS.
> [PARTOPS-858] Update QuAC doc with webintent URL

- docs/_build/triggers/hook-trigger.md
Fixing syntax on bundle.targetUrl.
> PLATSUPP-988 - Update hook-trigger.md

- docs/_embed/benefits-embedding.md
https://zapierorg.atlassian.net/browse/PLATSUP-1006
> PLATSUP-1006 Add Embed Blurb

- docs/_quickstart/build-private-integration.md
- docs/_quickstart/developer-tools/get-help.md
- docs/_reference/ai-actions.md
- docs/_reference/cli-docs.md
Slack thread: https://zapier.slack.com/archives/C063QL6RT0R/p1703685938313959
I also added some updates to the AI Actions reference page https://platform.zapier.com/reference/ai-actions to refer to 'AI Actions' and not 'Natural Language API' anymore.
> PLATSUP-1008 _ Updating the Developer Community links in the Platform Docs

- docs/_embed/solutions/partner-api.md
Resolves https://zapierorg.atlassian.net/browse/TPS-2928
> Remove mention of unexpired access tokens

- docs/_manage/account-and-team/add-team.md
Per Slack thread https://zapier.slack.com/archives/C02MX1VDYKF/p1704931925725259
> PLATSUPP-1010 - Add partner email subscription detail

- docs/_manage/integration-changes/rollout-cadence-iq-health-tips.md
- docs/_publish/launch-process/zap-templates.md
- docs/_publish/partner-program/benefits-guide.md
https://zapierorg.atlassian.net/browse/PLATSUP-1016
> [PLATSUP-1016] ZT FAQ PP Blurbs

- docs/_publish/launch-process/zap-templates.md
- docs/_publish/partner-program/benefits-guide.md
https://zapierorg.atlassian.net/browse/PLATSUP-1018
> PLATSUP-1018 Beautify new docs

- docs/_manage/integration-performance/user-feedback.md
- docs/_manage/versions/promote.md
- docs/_reference/cli.md
- Adding more awareness on how to close issues via the changelog or manually
> [PARTOPS-951] Add instructions on how to close issues after promotion

- docs/_publish/launch-process/zap-templates.md
- docs/_publish/partner-program/benefits-guide.md
https://zapierorg.atlassian.net/browse/PLATSUP-1021
> PLATSUP-1021 Update beta embed signups

- docs/_build/authentication/auth.md
- docs/_manage/integration-changes/auth-scheme.md
Update docs to hint at new option for partners to migrate between auth types.
> PLATSUP-1023 Doc update: Migrating between auth types

- docs/_manage/integration-changes/essential-tips-iq.md
- docs/_publish/launch-process/public-integration.md
- docs/_publish/partner-program/benefits-guide.md
- docs/_publish/partner-program/partner-faq.md
- docs/_publish/partner-program/partner-program.md
https://zapierorg.atlassian.net/browse/PLATSUP-1024
> PLATSUP-1024 Update beta/partner program pages in platform docs

- docs/_publish/validation/integration-checks-reference.md
Ran `generate_app_checks_doc` as specified in [this Coda doc](https://coda.io/d/_di0MgBhlCWf/Runbook_su88p#_luV0B) after submitting this MR: https://gitlab.com/zapier/zapier/-/merge_requests/56130
> [PDE-4558] Add D025 check to Integration Check Reference

- docs/_embed/embed-benefits.md
- docs/_publish/launch-process/user-help.md
https://zapierorg.atlassian.net/browse/PLATSUP-1028
> PLATSUP-1028 Update user help docs page in platform docs

- docs/_build/triggers/deduplication.md
Relates to the change in https://github.com/zapier/zapier-platform/pull/754, which will be released in v15.6.0.
> PDE-4686: Document about primary key

- docs/_build/advanced-features/env.md
- docs/_build/authentication/oauth.md
- docs/_manage/integration-changes/export-ui.md
- docs/_manage/integration-changes/planning-changes.md
- docs/_manage/versions/deprecate.md
- docs/_publish/launch-process/integration-publishing-requirements.md
- docs/_quickstart/developer-tools/ui-vs-cli.md
-adding use of env variables details
-typos and link updates
-clarifying the 'export to ui' process
-adding caveats for app version deletion
> PLATSUP-1030_adding_env_details

- docs/_manage/integration-performance/user-feedback.md
JIRA: https://zapierorg.atlassian.net/browse/PLATSUP-1031
Staged change: ![](https://cdn.zappy.app/62ecd077a2ae7e032a3e17183e516b97.png)
> PLATSUP-1031 Adds language for partners about auto-closing dormant issues.

- docs/_publish/launch-process/zap-templates.md
https://zapierorg.atlassian.net/browse/PLATSUP-1029
> PLATSUP-1029 Add ZT custom pill instructions

- docs/_publish/launch-process/zps.md
https://zapierorg.atlassian.net/browse/PLATSUP-1032
> PLATSUP-1032 Add ZPS to platform docs

- docs/_embed/solutions/partner-api.md
This PR updates https://platform.zapier.com/embed/partner-api#partner-api-endpoints to detail the new Authorization Code flow for partners (until the new Mintlify docs are live).
> TPS-3077 Partner API doc updates to describe authorization code flow

- docs/_publish/validation/integration-checks-reference.md
Syncs Integration Check Reference. Mainly edited the docs for `D010` and `T002` on how the `id` field restriction can be relaxed by primary key fields.
> PDE-4853: Sync integration check reference

- docs/_build/fields/dynamic-field.md
- docs/_build/triggers/pagination-trigger.md
- docs/_manage/integration-performance/error-handling.md
- docs/_manage/versions/migrate.md
Based on queue feedback/findings
-pagination page
-dynamic fields page
-migration of shared Zaps
-no 200s for errors
> PLATSUP-1035_doc updates

- docs/_manage/integration-performance/user-feedback.md
https://zapierorg.atlassian.net/browse/PLATSUP-1037
> PLATSUP-1037 Update ZIM link in platform docs

- _includes/head.html
- docs/_manage/integration-performance/user-feedback.md
https://zapierorg.atlassian.net/browse/PLATSUP-1044
> PLATSUP-1044 Update ZIM ZT

- docs/_build/authentication/apikeyauth.md
- docs/_build/authentication/basicauth.md
- docs/_build/authentication/oauth.md
- docs/_build/authentication/sessionauth.md
- docs/_build/authentication/subdomain-validation.md
-Add content for subdomain validation
-Link mentions of subdomain in auth docs to the new content
> PLATSUP-1048_subdomain_validation

- docs/_reference/cli-docs.md
Syncing cli docs back to Platform UI docs Reference
> PLATSUP-1048

- _includes/header.html
> [PDE-5021] Rename "Build integrations" to "How to build".

- docs/_publish/branding/branding-guidelines.md
- docs/_publish/launch-process/zap-templates.md
https://zapierorg.atlassian.net/browse/PLATSUP-1049
> [PLATSUP-1049] Add service categories to platform docs

- docs/_publish/branding/branding-guidelines.md
https://zapierorg.atlassian.net/browse/PLATSUP-1050
> [PLATSUP-1050] Fix markdown headings

- docs/_publish/validation/integration-checks-reference.md
Ran generate_app_checks_doc as specified in [this Coda doc](https://coda.io/d/_di0MgBhlCWf/Runbook_su88p#_luV0B) after submitting this MR: https://gitlab.com/zapier/zapier/-/merge_requests/57570
Screenshot:
> [PDE-5082] Add D026 check to Integration Check Reference

- docs/_publish/branding/branding-guidelines.md
- docs/_publish/launch-process/zap-templates.md
https://zapierorg.atlassian.net/browse/PLATSUP-1052
> PLATSUP-1052 Add branding FAQ to platform docs

- docs/_publish/partner-program/benefits-guide.md
https://zapierorg.atlassian.net/browse/PLATSUP-1053
> PLATSUP-1053 Update partner program benefits guide

- docs/_publish/launch-process/zps.md
https://zapierorg.atlassian.net/browse/PLATSUP-1058
> PLATSUP-1058 Update ZPS FAQ

- docs/_build/fields/line-items.md
- docs/_build/testing/test-auth.md
- docs/_build/testing/test-monitoring.md
- docs/_build/triggers/hook-trigger.md
- docs/_manage/integration-performance/embed-activation.md
- docs/_publish/launch-process/zap-templates.md
- docs/_quickstart/how-it-works/zapier-integration-structure.md
Update the following sections for clarity:
-line items
-rest hook trigger
-testing auth
-zap templates
-monitoring heading
-insights terminology
> PLATSUP-1059

- _config.yml
Follows up on https://github.com/zapier/visual-builder/pull/324 from almost two years ago 😄
> PDE-5174: bump partner count to 7,000+

- docs/_publish/launch-process/integration-build-guidelines.md
- docs/_publish/launch-process/integration-publishing-requirements.md
Resolving typos and headings to sentence case for new Publishing docs
> PLATSUP-1060_corrections

- docs/_publish/launch-process/integration-build-guidelines.md
Resolving bullet spacing for dates
> PLATSUP-1060_bullet_spacing

- docs/_manage/account-and-team/add-team.md
https://zapierorg.atlassian.net/browse/PARTOPS-1141
> [PARTOPS-1141] Add contact labels to platform docs

- docs/_publish/partner-program/benefits-guide.md
https://zapierorg.atlassian.net/browse/PARTOPS-1196
> PARTOPS-1196 Update benefits guide in platform docs

- docs/_quickstart/developer-tools/get-help.md
https://zapierorg.atlassian.net/browse/PLATSUP-1066
> [PLATSUP-1066] Add new "Build Faster with Zapier Experts" Section

- docs/_publish/launch-process/zap-templates.md
https://zapierorg.atlassian.net/browse/PARTOPS-1205
> PARTOPS-1205 Add new ZT rejection reason to platform docs

- docs/_build/testing/test-canary-testing.md
- docs/_build/testing/test-monitoring.md
- docs/_build/testing/test-tools.md
Looking to add a new page that will illustrate tools that will help integration developers test changes before pushing them out to their users.
> Testing tools doc

- docs/_build/triggers/trigger.md
Add information in regards to the identity confirmation that is supported by Zapier - https://zapierorg.atlassian.net/browse/PLATSUP-1072
> Update rest Hook information in regards to Identity confirmation

- docs/_quickstart/must-have-triggers-and-actions.md
Per feedback from a Partner and the partner manager team - https://zapier.slack.com/archives/C034FE1KP45/p1728316999881839
> [PARTOPS-1242] Rename Must Haves doc to Recommended triggers and actions

- docs/_quickstart/developer-tools/cli-tutorial.md
Updates the CLI tutorial with the new `invoke` command. Also updates some contents along the way.
> PDE-5323: Update CLI tutorial with the invoke command
