docs/_cli_tutorials/resthooks.md

We do not require you to send the unsubscribeHook request as a DELETE. Removing that sentence from the document to avoid confusion.

Remove DELETE requirement from Step 2

---

docs/_docs/advanced.md

We have a note that says you should only use computed fields with session or OAuth v2. But then just below that we reference an API key in the example.
This has caused some confusion for developers trying to include computed fields with Visual Builder apps using API Key auths.

Remove computed field API-Key example text

---

docs/_docs/start.md

Zapier doesn't accept logo image files that are larger than 2048x2048 pixels. 
This fails silently (says successful but the logo doesn't upload) when trying to upload the image in the developer portal.
Adding the maximum size restriction to the logo spec.

Update Logo Specs to include maximum size

---

_includes/toc.html
assets/stylesheets/elements/_typography.scss
docs/_docs/app-checks-reference.md
docs/_docs/export.md
docs/_docs/knownissues.md
docs/_docs/vs.md

This is mostly just copying data from the admin of the original style checks, plus a couple of small formatting tweaks to accommodate differences in markdown parsing between django and jekyll.
There's a known issue where our toc generator trips over certain headers. I've filed it (https://github.com/allejo/jekyll-toc/issues/23). We'll see if that's fixable or we can reformat the headers to avoid using `|`. 
The only big change is tweaking the css for `h2` to make the page read better. There are 4 ways we could lay out that page. Any strong feelings?
1. No change: 
2. Bigger `h2` (this PR, currently):
3. `<hr/>` between sections: 
4. Both of the above:

add style check doc

---

CONTRIBUTING.md
README.md

These changes update a small typo ('not' to 'now') in the instructions for getting Visual Builder running locally, as well as clarifications to CONTRIBUTING.md.  
In addition, per feedback from @alejandronanez, I changed the designated default branch from `staging` to `master` and added a bit more instruction on the process of forking the repo through to creating a PR.

Add clarification to docs

---

docs/_docs/input-designer.md

https://github.com/zapier/zapier/issues/28474
We don't support File type for inputs in the Platform visual-builder. This removes reference to File type from docs.

Remove reference to File type for input-designer

---

docs/_partners/integration-review-guidelines.md

Reverting the last commit as it seems I didn't wait long enough for the first deploy and that was the accurate fix.

Add redirect from /partners/app-review-guidelines/ to integration review guidelines doc

---

docs/_cli_tutorials/getting-started.md

It removes duplicated "can" from the CLI tutorial.
Thanks.

Fix typo: removing duplicated "can"

---

docs/_docs/apikey.md

Fixes typos and grammar in API key docs
Used Grammarly to check for typos 
https://zapierorg.atlassian.net/browse/PDE-1243

[PDE-1243] Fixes typos and grammar in apikey docs

---

docs/_cli_docs/cli.md

Fixing some funky encoding or extra text from the `zapier promote` section of our platform docs
Confirmed it doesn't appear this way in the original CLI docs - https://zapier.github.io/zapier-platform/cli#promote

Remove funky encoding from 'promote' section

---

docs/_cli_docs/cli.md

This Partner pointed out in a T3 thread that the `zapier env` documentation on the platform site didn't match the new `env:set`, `env:unset`, `env:get` commands - https://secure.helpscout.net/conversation/1118856408/1731901?folderId=597475.

Update 'zapier env' portion of platform cli docs

---

docs/_partners/zap-templates.md

Just added examples to help clarify ZT copy style, and made the title of doc clearer so content easier to find.

Edits and examples for ZT docs

---

docs/_partners/feature-requests-bugs.md

We've [decided](https://zapier.slack.com/archives/C5Z9BP4U9/p1601352712046700) that even in the case of an API being deprecated we won't migrate users and zaps, so let's remove the docs saying that we will do that.
**Question:** Do we still want to say that we'll help migrate ZTs in the section right after this removed code?

remove promise to migrate in case of deprecation

---

docs/_docs/vs.md

There are a couple of references in the "vs" doc that mention UI export to CLI coming soon, but that export exists. Those references are replaced with links to the export doc and updated language.
**Before:**
**After**

[SUPPORTESC-100] Update references to export that say coming soon

---

docs/_cli_docs/docs.md

I'm not sure where this used to go - was it this page, or did we render that page as an anchor somewhere?

PDE-1820: Example CLI apps anchor link is dead

---

docs/_cli_docs/docs.md

We believe that due to tasks no longer being saved for 90 days, a callback posting after 30 days has a risk of failing, so the documentation should state 30 days as the max.

[SUPPORTESC-101] Change 90-day limit for callbacks to 30-day

---

docs/_docs/faq.md

Integration developers sometimes hit the 30-second timeout when creating apps in the builder, most often if they're using Code Mode, and our docs only mention it for the CLI. This addition clarifies that the same timeout applies to the visual builder as well.

[SUPPORTESC-105] Add info on 30-second timeout to Visual Builder docs

---

docs/_docs/actions.md
docs/_docs/faq.md
docs/_docs/triggers.md

This PR does a few things. Its main focus is to:
* Reorganize the information about sample data and output fields, moving more of it to the Triggers and Actions pages rather than the FAQ, and making it more specific to each use (as well as trying to make some of the common content more consistent). 
* Change the FAQ to refer to these pages instead of these pages referring to the FAQ.
[Slack context](https://zapier.slack.com/archives/C5Z9BP4U9/p1609787059096700). This did result in additional information duplication, which isn't ideal. I met with @megan-driscoll to talk about this & other IA concerns, so we can ideally improve on this in the future.
I also did some cleanup:
* Updated the process for deleting connections to reflect the new My Apps page
* Changed FAQ titles to sentence case …

[SUPPORTESC-106] Reorganize sample data / output fields info, add three-sample limit

---

.gitignore
docs/_cli_docs/docs.md
docs/_docs/input-designer.md

This docs addition provides more guidance to developers about use contexts when they are working with code for loading dynamic fields.
Related to https://github.com/zapier/zapier-platform/pull/303.

[SUPPORTESC-109] Add details about when dynamic fields are loaded

---

docs/_cli_docs/cli.md
docs/_cli_docs/docs.md

Copies the latest docs from https://github.com/zapier/zapier-platform.

PDE-1980: Update CLI docs for 10.1.3 release

---

docs/_docs/integration-checks-reference.md
docs/_docs/testing.md
docs/_partners/integration-review-guidelines.md

Tired: Task History
Wired: Zap History
😄 
This PR keeps our Platform docs wired! A note is included that the checks that relate to the Zap History use T for historical reasons.

[SUPPORTESC-114] Update Platform docs to use new Zap History nomenclature

---

_config.yml

All of these posts were removed in https://github.com/zapier/visual-builder/pull/169, but the section header was left out.

remove empty "Updates" section

---

_includes/side-nav.html

Follow up to #183, which left behind a nav value that was throwing an error during build. Confirmed locally it actually builds now!

remove missing nav value

---

docs/_docs/testing.md
docs/_docs/versions.md

This page is aimed at public apps, but version management is possible for private apps as well, except for Promotion, which is only meaningful for public apps. 
Added that as a note and did a general cleanup on the page.

[SUPPORTESC-139] Note that Promote isn't used for private apps, clean up versions page

---

docs/_docs/testing.md
docs/_partners/lifecycle-planning.md

Clarify that using the public invite link for an app adds users to every version (and some small cleanup).

[SUPPORTESC-141] Specifically mention link invite vs email invite behavior, cleanup

---

docs/_docs/integration-checks-reference.md

There was some additional discussion on appropriate text when I submitted https://github.com/zapier/zapier/pull/48065 to backport the work to the monolith, so this PR updates the docs to match that update closely.

[SUPPORTESC-126] Transfer update from z/z to docs

---

_layouts/post-toc.html
_layouts/post.html

Change the footer text of the platform docs to point to the new Partner contact form rather than Github issues for this repo.

[SUPPORTOOL-299] Update footer to point to Partner contact form

---

docs/_docs/integration-checks-reference.md

- Makes it clearer that the URL needs to be specified in Perform List
- Uses similar terminology as check `T006 `
- HelpScout: https://secure.helpscout.net/conversation/1474953799/2345789/

[SUPPORTESC-153] Update the integration-checks-reference.md for check `D006`

---

docs/_partners/lifecycle-planning.md

The instructions here still had the legacy builder, which apps can no longer go public from, and used an older screenshot from the current builder. This PR updates us to the current builder's current behavior.

[SUPPORTESC-161] Lifecycle Planning: Update publishing instructions and screenshot

---

docs/_partner_success_stories/close.md
docs/_partners/lifecycle-planning.md

For some reason the old Google Doc template no longer exists.
https://zapierorg.atlassian.net/browse/PDE-2406

[PDE-2046] Update template links to Google Doc that exists

---

docs/_cli_docs/cli.md
docs/_cli_docs/docs.md

Regenerate docs from the zapier-platform repo. Related PR: https://github.com/zapier/zapier-platform/pull/377.

SUPPORTESC-163: Update CLI v11 docs

---

docs/_legacy/scripting.md

Fix link from `platform.zapier.io` to `platform.zapier.com` on https://platform.zapier.com/legacy/scripting.

[PDE-2481] Correct link to platform.zapier.com

---

_config.yml

Fixes [PDE-2510](https://zapierorg.atlassian.net/browse/PDE-2510).
Normally, `platform.zapier.com/docs` should redirect to `platform.zapier.com/docs/zapier-intro`. But, when the `CNAME` was removed (for HTTPS reasons, see [slack](https://zapier.slack.com/archives/C5Z9BP4U9/p1622832930477800?thread_ts=1622831211.476100&cid=C5Z9BP4U9)), the redirect started defaulting to the github pages site, which is a 404. 
This is documented [here](https://github.com/jekyll/jekyll-redirect-from#prefix). I believe fixing `site.url` will get it working again; it's hard to test because it always worked locally.
I also removed the slack invite url that we no longer use.

probably fix redirects

---

docs/_partners/feature-requests-bugs.md

Fixes some misspellings and outdated descriptions of where to find things in the platform.

[SUPPORTESC-181] Cleanup on "How to Maintain a Zapier Integration"

---

docs/_docs/advanced.md

Also a bit of cleanup, as per usual. :)
Relates to https://github.com/zapier/zapier-platform/pull/401 - if it turns out we should include info for `bundle.cleanedRequest` as well, I'll need to update both.

[SUPPORTESC-179] Add note about bundle.rawRequest header format

---

docs/_partner_api/changelog.md
docs/_partner_api/endpoints.md

I also updated other parts of the endpoints docs that were not in sync with the current version.
Partner API changes: https://github.com/zapier/partnerapi/pull/111

TPS-1239: adds uuid to v1/zap-templates endpoint docs and changelog

---

docs/_partner_api/endpoints.md

This PR adds the scope needed to access the profiles/me endpoint
Double-check me on that:  It IS `profile` scope, right? 😅

TPS-1294 -- Add profile scope

---

docs/_docs/actions.md

Modification of the guidance on deletion actions to match other sources (e.g. [this section](https://zapier.com/developer/documentation/v2/planning-guide-v1/#delete-actions-are-not-recommended) of the legacy docs).
And some cleanup, including clarification of what happens with search results.

[SUPPORTESC-185] Match guidance on deletes with other resources

---

docs/_docs/auth.md

Fixing a broken link (the header for API key is https://platform.zapier.com/docs/api but it should be https://platform.zapier.com/docs/apikey)

[SUPPORTESC-190] Update broken link for API Key header

---

docs/_docs/triggers.md

Include a comment about cases where a REST Hook Perform may return an empty array.

[SUPPORTESC-198] Add a brief note about empty array returns for hooks

---

docs/_partners/integration-review-guidelines.md

[Alexis suggested](https://zapier.slack.com/archives/C4124H5DF/p1632266357126400?thread_ts=1632248178.118400&cid=C4124H5DF) we update the Integration Ownership part of the Integration Review Guidelines to fit the [new decision](https://coda.io/d/Integrations-Team_djhfQ4ItfBo/Allow-public-Partner-apps-using-WhatsApp-Business-API_suGWf#_lusNd) allowing apps (on certain conditions) using the WhatsApp Business API.

[INT-15697] Update integration ownership scenario to provide exception

---

docs/_embed/partner_api.md

Updating the changelog to use lists instead of headings so that items are not added as tertiary navigation items

[TPS-1427] Change changelog from headings to lists

---

docs/_embed/partner_api.md

Updated the prefill section with the proper URL formatting per web intent, also updated the screenshots to use the latest editor UX. 
Finally, I removed the section on how to provide a label for a value, due to the bug in web-intent service: 
- Discussion of bug here: https://zapier.slack.com/archives/CH0SN5V0V/p1637259867185900?thread_ts=1637100270.102100&cid=CH0SN5V0V
- Bug PR: https://github.com/zapier/zapier/pull/52426
Once the bug is resolved, I'll update the docs with the proper syntax and accompanying example

[TPS-1427] Update prefill section of Partner API docs

---

docs/_docs/constraints.md
docs/_docs/dedupe.md
docs/_partners/integration-examples.md
docs/_partners/integration-review-guidelines.md

This new doc covers much the same ground as https://platform.zapier.com/legacy/dedupe, but updated for the current platform. That way, we aren't linking to information a legacy platform from the new one, and it gets some freshening up.

[SUPPORTESC-298] Add deduplication info to current platform version docs

---

docs/_docs/actions.md
docs/_docs/advanced.md
docs/_docs/constraints.md
docs/_docs/export.md
docs/_docs/faq.md
docs/_docs/glossary.md
docs/_docs/integration-checks-reference.md
docs/_docs/knownissues.md
docs/_docs/search-create.md
docs/_docs/testing.md
docs/_docs/versions.md
docs/_docs/vs.md

When I added the "Deduplication" doc at order 11 in #274, I neglected to shift the rest of these down a notch, resulting in it being placed after Actions instead of after Triggers, as intended. This PR fixes that issue.
Now:
After fix:
There are no other changes to the order after these updates. 👍🏻

[SUPPORTESC-301] Fix sidebar ordering after adding dedupe page

---

docs/_docs/integration-checks-reference.md

The main purpose of this update is to add the list of requirements to T006, which is frequently a perplexing check for app developers.
While working on that, I also wanted to clarify some of the other language around Zap runs and 'live' data, and made a few general clarifying updates.
If / when this is approved, I'll make a second PR to update the same language in the main repo.

[SUPPORTESC-283] Clarify language for T checks in integration checks reference

---

docs/_docs/integration-checks-reference.md

This should be the final change to the integration checks for the T check details! 😅 
This Markdown output is almost entirely from the `generate_app_checks_doc` script after https://github.com/zapier/zapier/pull/53301 (I made a few tiny adjustments to minimize the diff for this review).
Most of it is just minor or whitespace changes from the code formatting, with the substantive change being the correction to Z001 not to refer to the Zap history, which isn't actually used in that check.

[SUPPORTESC-283] Re-match integration checks with code after T fixes

---

docs/_docs/integration-checks-reference.md

Add further details and links to the S001 validation check to prevent confusion and potential ticket load.
Based on personal notes and experience in tickets, S001 causes a lot of confusion from devs. The updates answer a very common question asked by devs in ticket escalations.

[PDE-3149] docs(ui): Update S001 Integration Check

---

docs/_docs/integration-checks-reference.md

Update the Integration Checks Reference text (linked from the [Vatidate Integration text](https://cdn.zappy.app/36418d63437d3017c0fb7eb6b4f0f9a8.png) in the Platform UI) to make it more helpful, reflect that tests aren't enforced if the app will remain private, and that publication is possible with outstanding warnings (only publishing tasks are needed).
This is also a source of confusion for devs. We receive many escalations asking about warnings before publication and whether publishing tasks need to be clear if the app intends to remain private.
I decided to make the update here instead of the text in the Platform UI so that completing the checks would still be implicitly encouraged, but devs will still find the extra details when they click on learn more.

[PDE-3149] docs(ui): Update Integration Checks Reference Intro

---

docs/_docs/constraints.md

We truncate integration errors at ~250 characters when displaying them in the UI, which is a useful constraint to be aware of. We had gotten a question from a dev about the display of a longer JSON error message they'd hoped to include for users, but which wasn't showing up.

[SUPPORTESC-349] docs(cli): Add section about error message length

---

docs/_embed/security.md

Update Embed Security page to include a note about the ADE and ZTE not requiring security

TPS-0: Update Security Page

---

docs/_docs/input-designer.md

Looks like a backtick (`) accidentally made its way into the example code for a dropdown menu, making it awkward if someone copy/pastes it into their integration before editing. Removing it makes the example valid JSON again.

[SUPPORTESC-350] Remove erroneous backtick

---

docs/_partners/integration-review-guidelines.md

Prompted from [Alexis's question](https://zapier.slack.com/archives/C4124H5DF/p1654632957561919) regarding if we still push back on integrations with more than 5 triggers, actions, or searches. This is not longer a requirement of the app review, so we are removing it from the integration requirements.
For context, this used to be a requirement when app reviews involved testing every trigger/action/search manually.

[PARTOPS-70] Remove maximum number of t/a/s requirements

---

docs/_cli_docs/cli.md

An earlier [PR](https://github.com/zapier/visual-builder/pull/314) adds the collaborator to `team:get`. I'm enriching `team:add` accordingly as well.

[PDE-3249] Add collaborator to team:add

---

docs/_docs/basic.md

Since we [deployed authentication fields for Basic Auth](https://zapier.slack.com/archives/CEZDM0PQB/p1641568864025100), we haven’t updated VB docs to reflect this addition. Currently, there’s no mention of the fields for Basic Auth, just for Session and API Key.
The context is here, including the ticket that triggered this change:
* https://zapierorg.atlassian.net/browse/SUPPORTESC-365
I leveraged the text available for API Key and edited it to fit the needs and functionality of Basic auth: https://platform.zapier.com/docs/apikey#add-an-api-key-input-form

[SUPPORTESC-365] Update Basic Auth to include form fields

---

docs/_docs/advanced.md
docs/_docs/apikey.md
docs/_docs/auth.md
docs/_docs/basic.md
docs/_docs/digest.md
docs/_docs/oauth.md
docs/_docs/session.md

The platform UI docs do have details about creating connection labels, but the hoisting we do to pull authData and inputData keys up to the top level wasn’t mentioned, even though it's used implicitly in some of the instructions. 
We also didn't mention that it didn’t apply in Code Mode, and a lot of emphasis was placed on the different bundle names, which isn’t strictly necessary given the hoisting.
My goal is to update the way we talk about data for connections labels so it’s consistent wherever it comes up, and refers back to the main section in the auth doc if appropriate.

[SUPPORTENG-393] Auth: updates related to Connection Label

---

docs/_docs/auth.md

Final small adjustment about how to refer to the effect of adding data to connection labels, from [this thread](https://github.com/zapier/visual-builder/pull/327#discussion_r948601063) in #327 .

[SUPPORTESC-393] Label language adjustment

---

docs/_embed/partner_api.md

Update the changelog and v1/zaps description to reflect the update made to the endpoint.

TPS-1940 - Remove restriction on param filtering for v1 zaps

---

docs/_docs/constraints.md

Adds information about file hydration size limits to Constraints doc.
This constraint isn't frequently hit, but it's useful to have details on it here to supplement our existing hydration docs.

[SUPPORTENG-440] Add hydration constraint(s)

---

_includes/toc.html
assets/stylesheets/components/_toc.scss

The current table of contents (TOC) sidebar lists all topics and subtopics in a single column, with no clear distinction between elements. That makes pages with many topics, like "Zapier Platform CLI Docs" (pictured below) difficult to parse.
This update adds an indentation and marker to all sub-topics, allowing for more clear delineation between topics. Additionally, it removes the top-level header from the TOC, as H1 is typically reserved for the page title. This allows each of a page's primary topic to be more prominent in the TOC. Example of the same doc with these changes applied pictured below.

[SUPPORTENG-446] Indent TOC sub-topics

---

docs/_docs/testing.md

The _Testing_ doc currently has screenshots that are out-of-date. This PR updates the doc to use screenshots that reflect the latest UI.
For example, this screenshot of the Zap Editor:
Is updated to this:

[SUPPORTENG-449] Updates screenshots in "Testing"

---

docs/_cli_docs/docs.md

Make clear when to pull `bundle.inputData` and `bundle.authData` during different auth operations.

[PDE-2779] Distinction between bundle.inputData and bundle.authData.

---

docs/_partners/zap-templates.md

Remove mention that Zap Templates can be built for integrations that are pending publishing.

SUPPORTENG-451_zaptemplate_update

---

_includes/header.html

This update adds a "Help" link to main navigation while viewing documentation, making it easier to access the developer contact form. This is similar to the recent update to developer.zapier.com (SUPPORTENG-448).
Before:
After:

[SUPPORTENG-452] Add "Help" link to main nav

---

README.md
_includes/header.html
_includes/search.html
_includes/side-nav.html
_layouts/search.html
assets/stylesheets/base.scss
assets/stylesheets/components/_search.scss
search.md
search/content.json

As Google continues to shift its business model for its search features towards displaying ads, the Google-enhanced search bar becomes less useful. Currently, most searches include 3 to 5 ads before the actual results (requiring the user to scroll), and in some cases (such as when your search includes the word "Zapier") that includes ads for our competitors.
For example, when they search "how to build a Zapier integration", the user is presented with ads for Tray.io and MuleSoft:
This update uses Jekyll's features to create a JSON file of all articles, then adds javascript to filter and sort that JSON based on the user's search query. The results are then displayed on a search page in order of relevance:
> *Note:* Articles can also be omitted from search results by adding `search_omit: …

[SUPPORTENG-453] Replace Google Search plugin with internal solution

---

_includes/header.html
_includes/javascript.html
assets/stylesheets/base.scss
assets/stylesheets/elements/_image-zoom.scss

The images in our documentation often have a lot of text, and while alt text is helpful for some users, the ability to zoom in on images would allow users that need it to ready that text more easily.
This update adds a basic zoom functionality to all images within the content of a document, activated by clicking on them. The zoom can then be cancelled by clicking the image again, clicking the "X" button, or using the escape key on a keyboard.
Example:
* Before zoom: https://cdn.zappy.app/14c83fe97b567499aa319869ad950654.png
* Zoom applied on click: https://cdn.zappy.app/d8f9b5b01fc0a00d065430f7c7dc28fe.png
* GIF of the zoom in action: https://cdn.zappy.app/27fb41c9355ac0c2e003f79863323544.gif
This addresses issue #195

[SUPPORTENG-450] Add zoom function to images

---

docs/_docs/oauth.md

Here, I've updated the [Key bullet point](https://platform.zapier.com/docs/oauth#add-an-oauth-input-form-optional:~:text=Key%3A%20The%20internal%20name%20for%20your%20field%2C%20used%20to%20reference%20this%20field%20in%20Zapier%20API%20calls.%20For%20convenience%2C%20use%20the%20same%20key%20as%20your%20API%20uses%20for%20this%20field.) in the "Authentication — OAuth v2" to note that `client_id` and `client_secret` cannot be used as input form keys.
In testing, documented in the Slack threads linked in the accompanying Jira ticket, it appears `client_id` in particular conflicts with the similarly named environment variable, causing issues in the token request. This can be avoided by refraining from using these key names in input form fields in the OAuth2 config.

[SUPPORTENG-481] Updated OAuth2 Input Form section to note key limitations

---

docs/_embed/security.md

These changes update the `Embed` ➡️ `Security` page to encourage Partner's to update their domains instead of emailing `partners@zapier.com`

Add instructions for embedding domains on the Developer Platform

---

docs/_partners/lifecycle-planning.md

The text below the ZTE is right up against it, this adds line breaks to create spacing

Add spacing below the ZTE on Lifecycle Planning page

---

_config.yml
docs/_cli_docs/docs.md

Adding cli_version variable to config file, to replace the hard coded value, similar to how partner_count is used in multiple places including here: https://github.com/zapier/visual-builder/blob/master/docs/_partners/planning-guide.md

SUPPORTENG-537_add_cli_version_variable

---

docs/_partners/planning-guide.md

Add note re trademark/copyright identifiers aren't allowed in integration title (but are in description copy).

SUPPORTENG-757_cannot_include_trademark

---

docs/_cli_docs/cli.md
docs/_cli_docs/docs.md

This PR was created following [this Coda guide](https://coda.io/d/Team-Developer-Platform_di0MgBhlCWf/Syncing-CLI-Docs_su6uK#_luVds) on how to sync docs across repos! 
Here we are updating the docs after the latest v13 release (see PR here: https://github.com/zapier/zapier-platform/pull/611)

PDE-3738: Sync docs from v13 zapier-platform release

---

docs/_partners/integration-quality.md

Update doc to include specific info on integration insights for the GA launch.
This is how the definitions table will look - should I move the table up under the "How to view insights section"?

[PARTOPS-198] Update integration insights doc

---

docs/_docs/input-designer.md

We had a dev who was concerned about the fact that we display values in the dropdown menu that represent what the API requires but aren't user-friendly (even if there is also a user-friendly label). This addition gives context on why it's important to have both.
I also did some general wording cleanup/clarification in this area.

[SUPPORTENG-817] Dropdown data: why Zapier shows API values in menus

---

_config.yml
_includes/side-nav.html
docs/_private_integration/private_integration_rate_limits.md

Private integrations have increased rate limits for Team and Company plans. More details in this jira issue: https://zapierorg.atlassian.net/jira/software/c/projects/UDOCS/boards/283?modal=detail&selectedIssue=UDOCS-1190
Currently, we don't have space in the existing IA to insert this information. I've created a new category called "Private Integrations", as we have other new docs that we will be releasing shortly.
Note: the new category "Private Integrations" is a temporary solution and will be overhauled later this year as part of the work for #overhaul-platform-docs.
I've also updated the category titles to follow sentence case.

[UDOCS-1190] Private integrations: rate limit update docs

---

_config.yml
_includes/side-nav.html
docs/_zapier_products/natural_language_actions_api.md
docs/_zapier_products/zapiers_chatgpt_plugin.md

This is a copy of the following PR: https://github.com/zapier/visual-builder/pull/428. That PR had a typo in ` current_selection=current_section`, and I could not modify it. As we are looking to release this soon, I figured I would just re-create the PR and get it ready to merge!
Original description:
```
Created a new category called "Zapier products".
Created two new docs:
Natural Language Actions API
Zapier's ChatGPT Plugin
Do not publish, until Laura has reached out to confirm we are ready for these new docs and category to go live in the Platform docs.
```

[UDOCS-1383] new docs for NLA + Zapier's ChatGPT plugin

---

docs/_docs/oauth.md

This PR aims to fix this issue in the [PKCE documentation](https://platform.zapier.com/docs/oauth#add-pkce-support):

[PARTOPS-599] Remove typo in PKCE screenshot markdown

---

docs/_embed/partner_api.md
docs/_embed/zap_editor.md

The `/apps` endpoint of the Partner API now supports returning `app_latest`, which represents the SelectedAPI and production version of an app to be used when constructing `create Zap` [prefilled editor URLs](https://platform.zapier.com/embed/zap-editor#creating-zaps-without-zap-templates).

[PARTOPS-604] Add Partner API `/apps` returning `app_latest`

---

docs/_docs/actions.md
docs/_docs/integration-checks-reference.md
docs/_docs/testing.md
docs/_docs/triggers.md
docs/_legacy/app-checks-reference.md
docs/_partners/integration-review-guidelines.md

We're removing the `important` field per [this epic](https://zapierorg.atlassian.net/browse/PDE-3962). 
Related references to that field need to be removed from the docs. This PR includes the following changes:

[PDE-3968] Remove Important field references from docs and checks reference

---

_includes/search.html

Currently the search is susceptible to XSS attacks 
This PR adds some functionality to sanitize the user input to remove any common HTML tags that may be relevant to an XSS 
Testing with this script:
`/search?q=%3Cimg%20src=x%20onerror=alert(document.cookie)%3E`
When adding the term in the search bar
When adding the term in the URL bar

PDE-3833 - Sanitize the search input

---

README.md
docs/_conversion/maintaining.md
docs/_conversion/steps.md
docs/_docs/actions.md
docs/_docs/triggers.md
docs/_legacy/docs.md
docs/_legacy/scripting.md
docs/_partners/common-migration-errors.md
docs/_partners/integration-review-guidelines.md
docs/_partners/planning-guide.md
index.md

We're removing the `important` field per [this epic](https://zapierorg.atlassian.net/browse/PDE-3962). 
References to that field and screenshots showing the deprecated selection dropdown need to be removed from the docs or updated.
We also realized that there are quite a few references to the outdated `schema.html` on Github pages -- therefore this PR also replaces links to those with links to `https://github.com/zapier/zapier-platform/blob/main/packages/schema/docs/build/schema.md`.

[PDE-3968] Remove remaining important references + update screenshots

---

docs/_docs/actions.md
docs/_docs/triggers.md

In https://github.com/zapier/visual-builder/pull/445, the screenshots for the Triggers and Actions pages were updated to reflect the updated designs (see [here](https://github.com/zapier/visual-builder/pull/445/files#diff-73e571120efdacc1bda24cdf566fab608a1b5491f41ec73e1421756c3debb2b9R26) for Actions and [here](https://github.com/zapier/visual-builder/pull/445/files#diff-81d5711918d87cb8764e32d9af78805821fcb334be9259de469281f4670c7e15R30) for Triggers). But looking at the first screenshots in the [triggers docs](https://platform.zapier.com/docs/triggers) and [actions docs](https://platform.zapier.com/docs/actions), they are still using the older designs with the "important" visibility option. I believe the replacement screenshots probably were meant to replace these "heading" screenshots …

[PDE-3968] Updating leftover screenshots for Actions and Triggers with new designs

---

docs/_partners/common-migration-errors.md
docs/_partners/developer-platform-help.md
docs/_partners/faq.md
docs/_partners/feature-requests-bugs.md
docs/_partners/integration-examples.md
docs/_partners/integration-quality.md
docs/_partners/integration-review-guidelines.md
docs/_partners/lifecycle-planning.md
docs/_partners/partner-faq.md
docs/_partners/partner-program.md
docs/_partners/planning-guide.md
docs/_partners/trusted-developers.md
docs/_partners/zap-templates.md
docs/_partners/zim.md

- Removed reference to old beta phase requirements
- Created two new articles:
-  About the Partner Program (moved as it was buried in Partner FAQ)
- Get help with the Developer Platform (moved as it was buried in Integration FAQ)
- Updated articles:
-  Build your first public integration on Zapier (previously, how to build and publish an integration
- Zapier integration review guidelines
I've updated the entire folder for Partners content:
- Reordered the docs
- Changed all titles and headers to sentence case
- Removed FAQ from page titles (URLs for existing pages are unaffected)
- Updated titles to reflect titles on the page
- Fix terminology on words that were incorrectly capitalised, in line with the Content and Messaging Guidelines.

[UDOCS-1654] Updates to Partner section - 90 days beta phase

---

docs/_embed/automatic_account_creation.md
docs/_embed/full_zapier_experience.md
docs/_embed/partner_api.md
docs/_embed/zap_templates.md

[Thread with Brian from TPS ](https://zapier.slack.com/archives/CH0SN5V0V/p1685472701821929)on adding embed example videos from the "Embed" tab of the developer platform to our platform docs.
Tested embedding the video on the [AAC page](https://platform.zapier.com/embed/automatic-account-creation) via this [PR](https://github.com/zapier/visual-builder/pull/454). The video embeds fine, just needed to set the correct sizing so the video content is more easily visible. The height and width of the video is adjusted in this PR!

[PARTOPS-666] Update embed platform docs with videos

---

docs/_docs/versions.md

This fixes a tiny typo in the Versioning doc's migration warning callout, where I'd previously entered an extra "the."
https://cdn.zappy.app/57eb583bcf00b70b1c1e95aa74eb3125.png

Fixing typo in migration warning callout in versioning doc

---

docs/_docs/triggers.md

-added detail for subscribe/unsubscribe/perform list 
-lower case for all editor mentions per style guide 
-added detail to hide instead of delete triggers if used in public apps

SUPPORTENG-816_rest_hook_testing_clarify

---

docs/_embed/zap_editor.md

This is not the final draft of this page as I'd like to add screenshots once the generator is launched to GA, but I think it's safe to release this content now so we have live links for the developer platform page, as it's not being promoted anywhere until the launch of the generator.

[PARTOPS-668] Add prefill generator content to platform docs

---

_includes/search.html

This request aims to make `forwardSearch` and `backwardSearch` shallow copies of `queryTerms` in the `matchStrength` function, which determines the relevance of search results. 
At present, `forwardSearch` is a direct reference, so when we splice in the loop, we mutate `queryTerms`. As a result, `backwardSearch` gets initialized as an empty array, so AFAIK, we never actually run the backward search. 
I don't expect this to change search results much as it would really only affect queries of 3 words or more. But I think it's still work making the function work as it _appears_ it should work, and as the comment describes.

Fix search's matchStrength to allow backward search

---

README.md
docs/_cli_docs/docs.md
docs/_docs/export.md
docs/_docs/vs.md
docs/_legacy/import.md

Changes in this PR:
1. Fix deploy key link (reported [via Slack](https://zapier.slack.com/archives/C5Z9BP4U9/p1687177914762379))
* `https://zapier.com/developer/partner-settings/deploy-keys/ ` -> `https://developer.zapier.com/partner-settings/deploy-keys/`
2. Updated a few broken platform documentation links:
* `https://zapier.com/developer/start/introduction` -> `https://platform.zapier.com/cli_docs/docs#quick-setup-guide`
* `https://zapier.com/developer/start` -> `https://platform.zapier.com/cli_tutorials/getting-started`
3. Looks like some end-of-line encoding changes got included from my VSCode's autosave?

Fix: Broken Deploy Keys link and broken Platform docs links

---

docs/_partners/lifecycle-planning.md

In the Partners [Lifecycle Planning](https://platform.zapier.com/partners/lifecycle-planning) document, the ‘Partner Program’ in the ‘Public Phase’ section points to a Coda document (https://coda.io/d/_d-clruQiSri/_susbo#_luCcs)  instead of the actual partner program ([Zapier Partner Program: How Zapier Helps You Grow Your Company](https://zapier.com/platform/partner-program) ).
This needs to be updated in that public-facing doc.
Slack discussion: https://zapier.slack.com/archives/C037P154VMK/p1687333535143429

SUPPORTENG-915_Update-Partner-Program-Link

---

docs/_embed/full_zapier_experience.md
docs/_embed/security.md

* Remove two outdated bullets about embed domains
* Also clarifies on the FZE page what frameworks/langs you can generate code in - this was feedback from the FZE survey.

[PARTOPS-689] Remove two outdated bullets about embed domains

---

docs/_cli_docs/docs.md

Syncing CLI content as the latest core and Node versions do not yet match GitHub after the `15.0.1` release.

[SUPPORTENG-921] Syncing CLI docs with GitHub per v15.0.1 changes

---

docs/_embed/partner_api.md

Fixing two super quick copypasta issues found in the Partner API docs.

Fix category text in Partner API docs

---

index.md

The /docs should now redirect to the homepage. Tested locally and could not spot any issues.
* See issue report: https://zapier.slack.com/archives/C04P5J5R8E4/p1689341773107969?thread_ts=1689334102.378179&cid=C04P5J5R8E4
* Fix suggested by @jessveegee here: https://zapier.slack.com/archives/C04P5J5R8E4/p1689348494318529?thread_ts=1689334102.378179&cid=C04P5J5R8E4

Fix platform.zapier.com/docs infinite redirect loop

---

_includes/header.html

The underline under "Documentation" was accidentally removed in this PR: https://github.com/zapier/visual-builder/pull/477
Fix spotted by @robertscl 💯 https://zapier.slack.com/archives/C04P5J5R8E4/p1689367201972169?thread_ts=1689334102.378179&cid=C04P5J5R8E4

Fix: Add underline under "Documentation" in the header

---

docs/_manage/making-changes.md

* Updated matrix table to user markdown headers to center align text in all cells except the first column
* Separated column and matrix keys
* Added a disclaimer that any "Depends" without a link is too custom for generalized best practices - CTA to contact support.
* Added `-` to empty cells in last column of matrix
* Updated all enumerated bullets to regular bullets for consistency
* Added spaces and bullets to the last three convert and edit legacy app sections for better readability

[PARTOPS-633] Versioning matrix formatting

---

docs/_manage/analyze-integration-performance.md
docs/_publish/partner-faq.md
docs/_publish/partner-program.md
docs/_publish/public-integration.md

User reported to Ilia that [this section](https://platform.zapier.com/publish/partner-program-tips) in the documentation is throwing a 404.
* Fixed mentions of the broken link directly in the platform docs
* Added a redirect to the Partner Program Tips page in case that link is used/lingering elsewhere.

[PARTOPS-733] Add redirect and fix legacy links around docs

---

docs/_reference/cli-docs.md

This should help resolve some outstanding issues with callbacks we observe, at least during testing.
Though I seem to recall conversations about our sampling service supporting this natively. Did that ever happen?

Added recommendation for using `bundle.meta.isLoadingSample` to determine execution state in Zapier CLI documentation.

---

_config.yml
docs/_cli_docs/schema.md

https://zapierorg.atlassian.net/browse/PDE-4260
Context:
When building on the CLI tool, builders often use `zapier validate` to verify their app is written correctly.
```
cli-apps/taylorswift [ z validate                                                                                  ] 1:15 pm
Validating project locally
┌─────────────┬─────────────────────────────────────────────────────────────────────────┐
│ Property    │ App.authentication                                                      │
│ Message     │ additionalProperty "sus" exists in instance when not allowed            │
│ Links       │ https://platform.zapier.com/cli_docs/schema#authenticationschema@15.0.1 │
└─────────────┴─────────────────────────────────────────────────────────────────────────┘
Your integration is …
```

PDE-4260: Add invisible page that redirects to github schema docs

---

docs/_reference/cli-docs.md

We noticed a bug in at least one of our own integrations, and discovered the documentation has the same.
See https://zapierorg.atlassian.net/browse/INT-18028 and https://zapier.slack.com/archives/C053ZLBM4SV/p1692308220355109?thread_ts=1692208798.962019&cid=C053ZLBM4SV
cc @jessveegee

INT-18028 Cursor-based pagination fetches first page after fetching last

---

docs/_build/recommended-integration-features.md

- Phone & SMS table is not rendering as a table in the docs right now, wondering if it was because there wasn't a newline after the header.
- Added newlines in between tables for better readability

Format recommendation tables with newlines

---

docs/_reference/cli-docs.md

Sync CLI docs for the use of throttle configuration - https://github.com/zapier/zapier-platform/blob/main/packages/cli/README.md#adding-throttle-configuration

Sync CLI docs for version 15.4.1

---

docs/_reference/cli-docs.md

Previous docs would throw an error if `response.nextPage` was `null` which is often the case, this change ensures an empty string gets set in the cursor which allows the other code to work as expected.

Update cli-docs.md to reflect how to handle reaching the end of a result set for cursor pagination

---

.github/CODEOWNERS

Platform Support is in the process of overhauling the developer docs. And would like to be added as Codeowners and approvers of any future changes to the Visual Builder docs.

[SUPPORTENG-983] Add #team-platform-support as codeowners to Docs

---

docs/_reference/cli-docs.md

Syncing documentation changes from: https://github.com/zapier/zapier-platform/pull/720
To be merged after that release is merged and published.

Sync `cli-docs.md` to Release 15.4.2

---

docs/_publish/integration-publishing-guidelines.md

[PLATSUP-999](https://zapierorg.atlassian.net/jira/software/c/projects/PLATSUP/boards/655?selectedIssue=PLATSUP-999): Adding a section 8.3 to the publishing criteria to explain that dependencies must be kept up to date and that Zapier might request updates by a deadline.

[PLATSUP-999] Adding 8.3 regarding dependency updates

---

docs/_quickstart/must-have-triggers-and-actions.md
docs/_reference/use-cases/forms-app.md

Currently, URLs to /quickstart/integration-design-examples redirect to the forms reference,

[PARTOPS-861] Remove redirect to renamed "Must have trigger and actions" doc

---

_includes/javascript.html
_includes/prev-next.html

Nav for previous and next page were broken.
This fix uses JS which will find the ordered list of links. After finding the link that matches the current page, it will find the previous and next link by decrementing and incrementing the current index by one. 
We can then inject the two buttons and change the href and text with the corresponding link and texts.

PDE-4540 - Fix previous and next navigation links

---

docs/_quickstart/must-have-triggers-and-actions.md

Includes refinements made to the must-have data based on feedback provided:
- Replaced create or update actions
- Replaced new or updated triggers
- Replaced "Updated X in Stage/Status" to 3 separate with specific nouns

[PARTOPS-959] Update 'create or update' and 'new or updated' actions

---

docs/_embed/solutions/partner-api.md

This MR adds the correct trailing slash to https://zapier.com/oauth/authorize/.
Technically, `/authorize` redirects to `/authorize/`, so this isn't strictly necessary here, but as we move to authorization code flow, `/token/` must be used rather than `/token` (no redirect occurs), so we should stay consistent to avoid confusion.
See other updates: https://gitlab.com/zapier/public-api/public-api/-/merge_requests/134

TPS-3012 Adds the trailing slash to https://zapier.com/oauth/authorize/ documentation

---

docs/_embed/quick-account-creation.md

Update QuAC docs to include new use case for `/v2/authorize` URL. More info here - [https://zapierorg.atlassian.net/browse/TPS-2951](https://zapierorg.atlassian.net/browse/TPS-2951).

[PARTOPS-977] Add new authorize URL to QuAC doc under support for Partner API

---

docs/_embed/embed-benefits.md
docs/_embed/quick-account-creation.md
docs/_embed/solutions/full-zapier-experience.md
docs/_embed/solutions/partner-api.md
docs/_embed/solutions/zap-templates.md

Our new Partner embed gallery has launched! https://zapier.com/developer-platform/partner-embeds
Adding links to the gallery on the "Benefits" page of the Embed section, as well as links within each embed tool's respective page under the "Example implementation" sections.

[PARTOPS-1027] Add links to partner embed gallery

---

docs/_manage/account-and-team/add-team.md
docs/_quickstart/build-private-integration.md

This is a small test [before I push additional redirect changes](https://zapierorg.atlassian.net/browse/PLATSUP-1036). 
Context:
When running locally, Jekyll adds `/search/` to the path on the Search page, so redirects like `/quickstart/` alone do not work—at least, not without adding additional `/search/...` redirects.
However, we don't see `/search/` in the path in production, so this PR is intended to test if the redirect behaves as expected. If all goes as expected, I'll update the redirects for the other collections.
Acceptance criteria:
1. The Quickstart link in the sidebar continues to point to "Build your first private integration on Zapier"
2. The Quickstart collection link in search results also points to "Build your first private integration on Zapier" (currently goes to Manage …

[PLATSUP-1036] Switch quickstart collection redirect to match sidebar

---

docs/_build/actions/action.md
docs/_manage/account-and-team/add-team.md
docs/_publish/branding/branding-guidelines.md
docs/_reference/cli-docs.md

https://zapierorg.atlassian.net/browse/PLATSUP-1036 
The [previous PR](https://github.com/zapier/visual-builder/pull/611), intended as a test, worked as expected:
- The Quickstart link in the sidebar remained unchanged
- The Quickstart link in search results now points to the correct article
This PR adds additional redirections for these collections:
- Build
- Manage
- Publish
- Reference
Two quick notes:
First, if you test this PR locally, it will likely not work. For some reason, Jekyll adds `/search/` to collection link paths locally but not in prod.
Second, I've chosen not to update Embed. The sidebar link points to "Benefits" while the search results link points to the "Full Zapier Experience." I suspect there are places intentionally linking to `/embed/` as a path to info on the …

Update Build, Manage, Publish, and Reference collection redirects [PLATSUP-1036]

---

docs/_build/authentication/oauth.md
docs/_reference/cli-docs.md

The note on `redirect_uri` change becomes irrelevant with the stop to changing integrations' keys.

[PDE-4928] Remove note on redirect_uri change after publish

---

docs/_quickstart/developer-tools/ui-vs-cli.md
docs/_reference/legacy-scripting.md

Existing documentation: https://platform.zapier.com/quickstart/ui-vs-cli
Ticket from a partner that shows the need for this distinction to be added: https://zapier.zendesk.com/agent/tickets/1904585
Slack thread confirmation: https://zapier.slack.com/archives/C04P5J5R8E4/p1714494089511789
Specifying that handling long-running tasks via a callback URL is a CLI-only feature would be helpful in ticket deflection. I also made some link corrections in the "Scripting in converted Legacy Web Builder Integrations" doc

PLATSUP-1040: Add 'handing long running tasks via a callback URL' to the 'Platform UI vs CLI' doc

---

docs/_manage/integration-performance/user-feedback.md

[Loki Status project brief](https://coda.io/d/Team-Developer-Platform_di0MgBhlCWf/One-Pager-Loki-Issue-Statuses_su4o4#_lutLR)
Adding information about the new loki statues on the existing "Respond to user feedback and bugs" platform doc.

[PARTOPS-1028] Add loki status info to User Feedback doc

---

docs/_manage/integration-performance/user-feedback.md

Moving the new loki issue status content under the first bullet instead of at the bottom of the doc.

[PARTOPS- 1028] Move loki issue statuses section

---

docs/_manage/integration-performance/user-feedback.md

Adding a CTA to ZIM with a link to the ZIM section of the doc as [requested by Miranda.](https://zapier.slack.com/archives/C06QKAJDAVC/p1715183176987769)

[PARTOPS-1028] Add ZIM CTA to new issue statuses section

---

docs/_embed/partner-solutions.md

Partner and myself were confused with how to get to the new docs since it was the header that was linked. Removed header hyperlink and added links directly to the body content.

[PARTOPS-1066] Remove hyperlink from header which was confusing and add it to the body content

---

docs/_manage/integration-performance/embed-insights.md

Met with Product Marketing and Team Partner Sharing regarding transitioning embed docs from the original platform doc site to the new docs site (https://docs.api.zapier.com/guides/intro).
Michelle L. has added the embed insight definition content to the new doc site.
In order to move away focus on the "Embed" tab in the platform docs, this PR is to move existing embed insight definition doc under the "Manage > Integration Insights" section where all the other integration insight docs live.

[PARTOPS-1066] Move Embed insights doc under Manage

---

docs/_manage/integration-performance/embed-insights.md

Removing the redirect_from URL - https://platform.zapier.com/manage/embed-insights - as that's the new URL it's on, and updating full path redirect URL to partial path.

[PARTOPS-1066] Remove redirect_from URL

---

docs/_build/troubleshooting/operating-constraints.md
docs/_build/troubleshooting/troubleshoot-trigger-payload.md

-update from 6 MB to 20 MB per Slack thread https://zapier.slack.com/archives/C04P5J5R8E4/p1724267540358079?thread_ts=1724169354.974529&cid=C04P5J5R8E4

PLATSUP-1067 - update polling trigger payload limit

---

docs/_reference/cli.md

Adding `zapier pull` command to CLI reference (info here: https://platform.zapier.com/manage/versions#managing-versions-in-platform-cli)

[PARTOPS-1104] Add zapier pull to cli reference
